import SwiftUI

/// DEBUG-only onboarding step: pick which backend to pair against.
///
/// Why this exists: every family_id / device_id is generated by the
/// backend's DB during `/family/create` + `/family/pair`. If the user
/// pairs against backend A but later switches to backend B, those IDs
/// don't exist in B's DB and chat fails with "no child device paired".
/// Asking *before* pair guarantees the IDs are written for the right
/// backend from the start.
///
/// Release builds skip this step entirely — production parents only
/// ever see one backend.
struct BackendChoiceStep: View {
    @EnvironmentObject var apiClient: APIClient
    let onContinue: () -> Void

    /// Local source-of-truth — only flushed to `apiClient.saveServerURL`
    /// when the user taps Continue. Avoids writing every tap of the
    /// segmented picker (which would cause `onChange` cascade fires in
    /// the Settings picker code path).
    @State private var selection: String = APIClient.localDevURL

    var body: some View {
        VStack(spacing: Spacing.section) {
            VStack(spacing: Spacing.lg) {
                Text("Backend")
                    .font(.evHeadlineLarge)
                    .foregroundStyle(Color.evPrimary)
                    .multilineTextAlignment(.center)
                Text("DEBUG build only — pick which backend you want this device to pair against. Family + device IDs only exist in the backend they were generated on.")
                    .font(.evBodyMedium)
                    .multilineTextAlignment(.center)
                    .foregroundStyle(Color.evOnSurfaceVariant)
                    .padding(.horizontal, Spacing.xl)
            }
            .padding(.top, Spacing.section)

            Spacer()

            VStack(alignment: .leading, spacing: Spacing.lg) {
                Picker("Backend", selection: $selection) {
                    Text("Local (192.168.1.175)").tag(APIClient.localDevURL)
                    Text("Production (Render)").tag(APIClient.defaultURL)
                }
                .pickerStyle(.segmented)

                VStack(alignment: .leading, spacing: 4) {
                    Text("Selected:")
                        .font(.evBodySmall)
                        .foregroundStyle(Color.evOutline)
                    Text(selection)
                        .font(.system(size: 13, design: .monospaced))
                        .foregroundStyle(Color.evOnSurface)
                        .textSelection(.enabled)
                }
            }
            .padding(.horizontal, Spacing.xl)

            Spacer()

            Button {
                // Commit selection BEFORE leaving the step — the next
                // onboarding step (parentPairingCode or childEnterPairingCode)
                // immediately uses `apiClient.baseURL` for its first
                // /family/pair or /family/create call.
                apiClient.saveServerURL(selection)
                onContinue()
            } label: {
                Text("Continue")
                    .font(.evLabelLarge)
                    .frame(maxWidth: .infinity)
                    .foregroundStyle(Color.evOnPrimary)
                    .padding(.vertical, Spacing.lg)
                    .background(
                        RoundedRectangle(cornerRadius: CornerRadius.md)
                            .fill(Color.evPrimary)
                    )
            }
        }
        .padding(Spacing.xl)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(Color.evSurface)
        .onAppear {
            // Pre-seed selection from whatever the user previously chose,
            // if any — repeat onboardings shouldn't reset their backend.
            let saved = apiClient.baseURL.trimmingCharacters(in: .whitespacesAndNewlines)
            if saved == APIClient.localDevURL || saved == APIClient.defaultURL {
                selection = saved
            }
        }
    }
}
